export const MOCK_EMPLOYEE_LIST = [
  {
    id: "1",
    public_id: "TmdPXUzN",
    username: "123",
    email: "arunprav5@gmail.com",
    phone: "7339196316",
    first_Name: "Aaadhithya",
    last_Name: "Raavanan",
    full_Name: "Aaadhithya Raavanan",
    level: 1,

    role: "CEO",
    department: "Management",
    date_of_birth: "2001-07-30",
    gender: "male",
    address: "Coorg, karnataka",
    password: "123",
    educations: [
      {
        degree_name: "MBA",
        university_name: "IIM Bangalore",
        graduation_year: 2023,
      },
      {
        degree_name: "B.Tech",
        university_name: "Anna University",
        graduation_year: 2019,
      },
    ],
    emergency_contacts: [
      {
        name: "Pravin Arun",
        phone: "9123456780",
        address: "Coimbatore, Tamil Nadu",
      },
    ],
  },

  {
    id: "2",
    public_id: "Abc123Xy",
    username: "nandha01",
    email: "nandha01@gmail.com",
    phone: "9876543210",
    first_Name: "Nandha",
    last_Name: "Kumar",
    full_Name: "Nandha Kumar",
    level: 2,

    role: "CTO",
    department: "Technology",
    date_of_birth: "1998-03-15",
    gender: "male",
    address: "Chennai, Tamil Nadu",
    password: "Nandha@123",
    educations: [
      {
        degree_name: "M.Tech",
        university_name: "IIT Madras",
        graduation_year: 2021,
      },
      {
        degree_name: "B.Tech",
        university_name: "Anna University",
        graduation_year: 2019,
      },
    ],
    emergency_contacts: [
      {
        name: "Kavitha Kumar",
        phone: "9876501234",
        address: "Chennai, Tamil Nadu",
      },
    ],
  },
  {
    id: "3",
    public_id: "Jkl321Po",
    username: "ananya_hr",
    email: "ananya.hr@gmail.com",
    phone: "8801234567",
    first_Name: "Ananya",
    last_Name: "Menon",
    full_Name: "Ananya Menon",
    level: 2,

    role: "HR Manager",
    department: "Human Resources",
    date_of_birth: "1997-12-08",
    gender: "female",
    address: "Kochi, Kerala",
    password: "Ananya@123",
    educations: [
      {
        degree_name: "MBA HR",
        university_name: "XLRI Jamshedpur",
        graduation_year: 2020,
      },
      {
        degree_name: "BBA",
        university_name: "Kerala University",
        graduation_year: 2018,
      },
    ],
    emergency_contacts: [
      { name: "Menon Ananya", phone: "9901234567", address: "" },
    ],
  },
  {
    id: "4",
    public_id: "Fin201Xx",
    username: "raja_cfo",
    email: "raja.cfo@company.com",
    phone: "9123456780",
    first_Name: "Raja",
    last_Name: "Narayanan",
    full_Name: "Raja Narayanan",
    level: 2,

    role: "CFO",
    department: "Finance",
    date_of_birth: "1990-05-14",
    gender: "male",
    address: "Chennai, Tamil Nadu",
    password: "Raja@123",
    educations: [
      {
        degree_name: "Chartered Accountant",
        university_name: "ICAI",
        graduation_year: 2014,
      },
      {
        degree_name: "B.Com",
        university_name: "Madras University",
        graduation_year: 2011,
      },
    ],
    emergency_contacts: [
      {
        name: "Nalini Narayanan",
        phone: "9123456799",
        address: "Chennai, Tamil Nadu",
      },
    ],
  },
  {
    id: "5",
    public_id: "Ops202Yy",
    username: "deepa_coo",
    email: "deepa.coo@company.com",
    phone: "9345678901",
    first_Name: "Deepa",
    last_Name: "Ravi",
    full_Name: "Deepa Ravi",
    level: 2,

    role: "COO",
    department: "Operations",
    date_of_birth: "1992-09-23",
    gender: "female",
    address: "Bangalore, Karnataka",
    password: "Deepa@123",
    educations: [
      {
        degree_name: "MBA Operations",
        university_name: "IIM Ahmedabad",
        graduation_year: 2017,
      },
      {
        degree_name: "B.Sc Logistics",
        university_name: "Bangalore University",
        graduation_year: 2014,
      },
    ],
    emergency_contacts: [
      { name: "Ravi Deepa", phone: "9445567788", address: "" },
    ],
  },
  {
    id: "6",
    public_id: "Tech300Aa",
    username: "karthik_lead",
    email: "karthik.lead@company.com",
    phone: "9898765432",
    first_Name: "Karthik",
    last_Name: "Sundar",
    full_Name: "Karthik Sundar",
    level: 3,

    role: "Tech Lead",
    department: "Technology",
    date_of_birth: "1995-07-12",
    gender: "male",
    address: "Bangalore, Karnataka",
    password: "Karthik@123",
    educations: [
      {
        degree_name: "M.Tech",
        university_name: "IIT Delhi",
        graduation_year: 2018,
      },
      {
        degree_name: "B.Tech",
        university_name: "Anna University",
        graduation_year: 2016,
      },
    ],
    emergency_contacts: [
      { name: "Sundar Karthik", phone: "9898701234", address: "" },
    ],
  },
  {
    id: "7",
    public_id: "Fin301Bb",
    username: "meena_finlead",
    email: "meena.finlead@company.com",
    phone: "9123098765",
    first_Name: "Meena",
    last_Name: "Krishnan",
    full_Name: "Meena Krishnan",
    level: 3,

    role: "Finance Lead",
    department: "Finance",
    date_of_birth: "1994-11-21",
    gender: "female",
    address: "Chennai, Tamil Nadu",
    password: "Meena@123",
    educations: [
      {
        degree_name: "MBA Finance",
        university_name: "IIM Bangalore",
        graduation_year: 2019,
      },
      {
        degree_name: "B.Com",
        university_name: "Madras University",
        graduation_year: 2015,
      },
    ],
    emergency_contacts: [
      { name: "Krishnan Meena", phone: "9123456789", address: "" },
    ],
  },
  {
    id: "8",
    public_id: "HR302Cc",
    username: "ravi_hrlead",
    email: "ravi.hrlead@company.com",
    phone: "9887654321",
    first_Name: "Ravi",
    last_Name: "Subramani",
    full_Name: "Ravi Subramani",
    level: 3,

    role: "HR Lead",
    department: "Human Resources",
    date_of_birth: "1990-09-20",
    gender: "male",
    address: "Boston, USA",
    password: "Logan@123",
    educations: [
      {
        degree_name: "MBA HR",
        university_name: "Boston University",
        graduation_year: 2015,
      },
    ],
    emergency_contacts: [
      { name: "Amelia Morgan", phone: "9100133447", address: "Boston, USA" },
    ],
  },
  {
    id: "34",
    public_id: "EMP034",
    username: "zoe_king",
    email: "zoe.king@example.com",
    phone: "9100144557",
    first_Name: "Zoe",
    last_Name: "King",
    full_Name: "Zoe King",
    level: 3,

    role: "Finance Lead",
    department: "Finance",
    date_of_birth: "1988-12-15",
    gender: "female",
    address: "Dallas, USA",
    password: "Zoe@123",
    educations: [
      {
        degree_name: "M.Com",
        university_name: "Texas University",
        graduation_year: 2014,
      },
    ],
    emergency_contacts: [
      { name: "Ethan King", phone: "9100144558", address: "Dallas, USA" },
    ],
  },
  {
    id: "35",
    public_id: "EMP035",
    username: "leo_walker",
    email: "leo.walker@example.com",
    phone: "9100155668",
    first_Name: "Leo",
    last_Name: "Walker",
    full_Name: "Leo Walker",
    level: 3,

    role: "Software Engineer",
    department: "Technology",
    date_of_birth: "1992-06-10",
    gender: "male",
    address: "San Jose, USA",
    password: "Leo@123",
    educations: [
      {
        degree_name: "B.Tech",
        university_name: "UC Berkeley",
        graduation_year: 2016,
      },
    ],
    emergency_contacts: [
      { name: "Mia Walker", phone: "9100155669", address: "San Jose, USA" },
    ],
  },
  {
    id: "36",
    public_id: "EMP036",
    username: "ella_roberts",
    email: "ella.roberts@example.com",
    phone: "9100166779",
    first_Name: "Ella",
    last_Name: "Roberts",
    full_Name: "Ella Roberts",
    level: 4,

    role: "Software Engineer",
    department: "Technology",
    date_of_birth: "1995-01-12",
    gender: "female",
    address: "Austin, USA",
    password: "Ella@123",
    educations: [
      { degree_name: "B.Tech", university_name: "MIT", graduation_year: 2018 },
    ],
    emergency_contacts: [
      { name: "Jack Roberts", phone: "9100166780", address: "Austin, USA" },
    ],
  },
  {
    id: "37",
    public_id: "EMP037",
    username: "sebastian_clark",
    email: "sebastian.clark@example.com",
    phone: "9100177880",
    first_Name: "Sebastian",
    last_Name: "Clark",
    full_Name: "Sebastian Clark",
    level: 4,

    role: "Operations Analyst",
    department: "Operations",
    date_of_birth: "1994-02-25",
    gender: "male",
    address: "Denver, USA",
    password: "Sebastian@123",
    educations: [
      {
        degree_name: "BBA",
        university_name: "Colorado University",
        graduation_year: 2016,
      },
    ],
    emergency_contacts: [
      { name: "Harper Clark", phone: "9100177881", address: "Denver, USA" },
    ],
  },
  {
    id: "38",
    public_id: "EMP038",
    username: "violet_martin",
    email: "violet.martin@example.com",
    phone: "9100188991",
    first_Name: "Violet",
    last_Name: "Martin",
    full_Name: "Violet Martin",
    level: 4,

    role: "HR Executive",
    department: "Human Resources",
    date_of_birth: "1996-09-15",
    gender: "female",
    address: "Boston, USA",
    password: "Violet@123",
    educations: [
      {
        degree_name: "BBA",
        university_name: "Boston University",
        graduation_year: 2018,
      },
    ],
    emergency_contacts: [
      { name: "Logan Martin", phone: "9100188992", address: "Boston, USA" },
    ],
  },
  {
    id: "39",
    public_id: "EMP039",
    username: "jackson_lewis",
    email: "jackson.lewis@example.com",
    phone: "9100199002",
    first_Name: "Jackson",
    last_Name: "Lewis",
    full_Name: "Jackson Lewis",
    level: 4,

    role: "Accountant",
    department: "Finance",
    date_of_birth: "1993-07-20",
    gender: "male",
    address: "Dallas, USA",
    password: "Jackson@123",
    educations: [
      {
        degree_name: "B.Com",
        university_name: "Texas University",
        graduation_year: 2015,
      },
    ],
    emergency_contacts: [
      { name: "Zoe Lewis", phone: "9100199003", address: "Dallas, USA" },
    ],
  },
  {
    id: "40",
    public_id: "EMP040",
    username: "ariana_hughes",
    email: "ariana.hughes@example.com",
    phone: "9100200113",
    first_Name: "Ariana",
    last_Name: "Hughes",
    full_Name: "Ariana Hughes",
    level: 4,

    role: "Software Engineer",
    department: "Technology",
    date_of_birth: "1995-10-10",
    gender: "female",
    address: "San Jose, USA",
    password: "Ariana@123",
    educations: [
      {
        degree_name: "B.Tech",
        university_name: "UC Berkeley",
        graduation_year: 2017,
      },
    ],
    emergency_contacts: [
      { name: "Leo Hughes", phone: "9100200114", address: "San Jose, USA" },
    ],
  },
  {
    id: "9",
    public_id: "Ops303Dd",
    username: "lakshmi_opslead",
    email: "lakshmi.opslead@company.com",
    phone: "9781234560",
    first_Name: "Lakshmi",
    last_Name: "Vijay",
    full_Name: "Lakshmi Vijay",
    level: 3,

    role: "Operations Lead",
    department: "Operations",
    date_of_birth: "1996-01-19",
    gender: "female",
    address: "Bangalore, Karnataka",
    password: "Lakshmi@123",
    educations: [
      {
        degree_name: "MBA Operations",
        university_name: "IIM Lucknow",
        graduation_year: 2019,
      },
      {
        degree_name: "BBA",
        university_name: "Bangalore University",
        graduation_year: 2016,
      },
    ],
    emergency_contacts: [
      { name: "Vijay Lakshmi", phone: "9781234590", address: "" },
    ],
  },
  {
    id: "10",
    public_id: "Mkt304Ee",
    username: "ajay_marklead",
    email: "ajay.marklead@company.com",
    phone: "9090909090",
    first_Name: "Ajay",
    last_Name: "Dev",
    full_Name: "Ajay Dev",
    level: 3,

    role: "Marketing Lead",
    department: "Marketing",
    date_of_birth: "1995-09-25",
    gender: "male",
    address: "Hyderabad, Telangana",
    password: "Ajay@123",
    educations: [
      {
        degree_name: "MBA Marketing",
        university_name: "IIM Bangalore",
        graduation_year: 2020,
      },
      {
        degree_name: "BBA",
        university_name: "Osmania University",
        graduation_year: 2016,
      },
    ],
    emergency_contacts: [
      { name: "Dev Ajay", phone: "9090909010", address: "" },
    ],
  },
  {
    id: "11",
    public_id: "Tech701Aa",
    username: "arjun_dev",
    email: "arjun.dev@company.com",
    phone: "9001122331",
    first_Name: "Arjun",
    last_Name: "Ravi",
    full_Name: "Arjun Ravi",
    level: 3,

    role: "Tech Lead",
    department: "Technology",
    date_of_birth: "1995-05-12",
    gender: "male",
    address: "Bangalore, Karnataka",
    password: "Arjun@123",
    educations: [
      {
        degree_name: "B.Tech",
        university_name: "IIT Madras",
        graduation_year: 2017,
      },
    ],
    emergency_contacts: [
      { name: "Ravi Arjun", phone: "9001122332", address: "" },
    ],
  },
  {
    id: "12",
    public_id: "HR702Bb",
    username: "megha_hr",
    email: "megha.hr@company.com",
    phone: "9112233445",
    first_Name: "Megha",
    last_Name: "Sharma",
    full_Name: "Megha Sharma",
    level: 3,

    role: "HR Lead",
    department: "Human Resources",
    date_of_birth: "1994-07-08",
    gender: "female",
    address: "Chennai, Tamil Nadu",
    password: "Megha@123",
    educations: [
      {
        degree_name: "B.Tech",
        university_name: "IIT Madras",
        graduation_year: 2017,
      },
    ],
    emergency_contacts: [
      {
        name: "Sharma Family",
        phone: "9112233446",
        address: "Chennai, Tamil Nadu",
      },
    ],
  },
  {
    id: "13",
    public_id: "Fin703Cc",
    username: "vikram_fin",
    email: "vikram.fin@company.com",
    phone: "9223344556",
    first_Name: "Vikram",
    last_Name: "Rao",
    full_Name: "Vikram Rao",
    level: 3,

    role: "Finance Lead",
    department: "Finance",
    date_of_birth: "1993-03-21",
    gender: "male",
    address: "Hyderabad, Telangana",
    password: "Vikram@123",
    educations: [
      {
        degree_name: "M.Com",
        university_name: "Osmania University",
        graduation_year: 2015,
      },
    ],
    emergency_contacts: [],
  },
  {
    id: "14",
    public_id: "Ops704Dd",
    username: "deepika_ops",
    email: "deepika.ops@company.com",
    phone: "9334455667",
    first_Name: "Deepika",
    last_Name: "Nair",
    full_Name: "Deepika Nair",
    level: 3,

    role: "Operations Lead",
    department: "Operations",
    date_of_birth: "1992-09-23",
    gender: "female",
    address: "Bangalore, Karnataka",
    password: "Deepika@123",
    educations: null,
    emergency_contacts: null,
  },
  {
    id: "15",
    public_id: "Mkt705Ee",
    username: "ajay_mark",
    email: "ajay.mark@company.com",
    phone: "9445566778",
    first_Name: "Ajay",
    last_Name: "Dev",
    full_Name: "Ajay Dev",
    level: 3,

    role: "Marketing Lead",
    department: "Marketing",
    date_of_birth: "1995-09-25",
    gender: "male",
    address: "Hyderabad, Telangana",
    password: "Ajay@123",
    educations: [
      {
        degree_name: "MBA",
        university_name: "ISB Hyderabad",
        graduation_year: 2018,
      },
    ],
    emergency_contacts: [
      { name: "Dev Family", phone: "9445566779", address: "" },
    ],
  },
  {
    id: "16",
    public_id: "Tech706Ff",
    username: "keerthi_dev",
    email: "keerthi.dev@company.com",
    phone: "9003214567",
    first_Name: "Keerthi",
    last_Name: "Devi",
    full_Name: "Keerthi Devi",
    level: 4,

    role: "Software Engineer",
    department: "Technology",
    date_of_birth: "2000-06-22",
    gender: "female",
    address: "Madurai, Tamil Nadu",
    password: "Keerthi@123",
    educations: null,
    emergency_contacts: null,
  },
  {
    id: "17",
    public_id: "Ops707Gg",
    username: "rajesh_ops",
    email: "rajesh.ops@company.com",
    phone: "9998745632",
    first_Name: "Rajesh",
    last_Name: "Raman",
    full_Name: "Rajesh Raman",
    level: 4,

    role: "Operations Analyst",
    department: "Operations",
    date_of_birth: "1995-02-10",
    gender: "male",
    address: "Bangalore, Karnataka",
    password: "Rajesh@123",
    educations: [
      {
        degree_name: "BBA",
        university_name: "Christ University",
        graduation_year: 2016,
      },
    ],
    emergency_contacts: null,
  },
  {
    id: "18",
    public_id: "Mkt708Hh",
    username: "sindhu_mark",
    email: "sindhu.mark@company.com",
    phone: "9876543211",
    first_Name: "Sindhu",
    last_Name: "Pillai",
    full_Name: "Sindhu Pillai",
    level: 4,

    role: "Marketing Specialist",
    department: "Marketing",
    date_of_birth: "1999-04-11",
    gender: "female",
    address: "Chennai, Tamil Nadu",
    password: "Sindhu@123",
    educations: null,
    emergency_contacts: null,
  },
  {
    id: "19",
    public_id: "Fin709Ii",
    username: "vimal_fin",
    email: "vimal.fin@company.com",
    phone: "9876501234",
    first_Name: "Vimal",
    last_Name: "Raj",
    full_Name: "Vimal Raj",
    level: 4,

    role: "Accountant",
    department: "Finance",
    date_of_birth: "1998-03-02",
    gender: "male",
    address: "Salem, Tamil Nadu",
    password: "Vimal@123",
    educations: [
      {
        degree_name: "B.Com",
        university_name: "Madras University",
        graduation_year: 2017,
      },
    ],
    emergency_contacts: null,
  },

  {
    id: "20",
    public_id: "HR710Jj",
    username: "geetha_hr",
    email: "geetha.hr@company.com",
    phone: "9812345678",
    first_Name: "Geetha",
    last_Name: "Anand",
    full_Name: "Geetha Anand",
    level: 4,

    role: "HR Executive",
    department: "Human Resources",
    date_of_birth: "1997-12-01",
    gender: "female",
    address: "Coimbatore, Tamil Nadu",
    password: "Geetha@123",
    educations: null,
    emergency_contacts: [
      {
        name: "Anand Family",
        phone: "9812345679",
        address: "Coimbatore, Tamil Nadu",
      },
    ],
  },
  {
    id: "21",
    public_id: "EMP021",
    username: "ethan_hill",
    email: "ethan.hill@example.com",
    phone: "9100011223",
    first_Name: "Ethan",
    last_Name: "Hill",
    full_Name: "Ethan Hill",
    level: 1,

    role: "CEO",
    department: "Management",
    date_of_birth: "1978-02-10",
    gender: "male",
    address: "New York, USA",
    password: "Ethan@123",
    educations: [
      { degree_name: "MBA", university_name: "Harvard", graduation_year: 2002 },
      { degree_name: "B.Sc", university_name: "MIT", graduation_year: 1998 },
    ],
    emergency_contacts: [
      { name: "Anna Hill", phone: "9100011224", address: "New York, USA" },
    ],
  },
  {
    id: "22",
    public_id: "EMP022",
    username: "olivia_green",
    email: "olivia.green@example.com",
    phone: "9100022334",
    first_Name: "Olivia",
    last_Name: "Green",
    full_Name: "Olivia Green",
    level: 2,

    role: "CTO",
    department: "Technology",
    date_of_birth: "1982-09-15",
    gender: "female",
    address: "San Francisco, USA",
    password: "Olivia@123",
    educations: [
      {
        degree_name: "M.Tech",
        university_name: "Stanford",
        graduation_year: 2008,
      },
      {
        degree_name: "B.Tech",
        university_name: "UC Berkeley",
        graduation_year: 2004,
      },
    ],
    emergency_contacts: [
      {
        name: "Liam Green",
        phone: "9100022335",
        address: "San Francisco, USA",
      },
    ],
  },
  {
    id: "23",
    public_id: "EMP023",
    username: "noah_scott",
    email: "noah.scott@example.com",
    phone: "9100033445",
    first_Name: "Noah",
    last_Name: "Scott",
    full_Name: "Noah Scott",
    level: 2,

    role: "CFO",
    department: "Finance",
    date_of_birth: "1979-06-20",
    gender: "male",
    address: "Chicago, USA",
    password: "Noah@123",
    educations: [
      {
        degree_name: "M.Com",
        university_name: "University of Chicago",
        graduation_year: 2003,
      },
      {
        degree_name: "B.Com",
        university_name: "University of Illinois",
        graduation_year: 2000,
      },
    ],
    emergency_contacts: [
      { name: "Sophia Scott", phone: "9100033446", address: "Chicago, USA" },
    ],
  },
  {
    id: "24",
    public_id: "EMP024",
    username: "isabella_wright",
    email: "isabella.wright@example.com",
    phone: "9100044556",
    first_Name: "Isabella",
    last_Name: "Wright",
    full_Name: "Isabella Wright",
    level: 2,

    role: "COO",
    department: "Operations",
    date_of_birth: "1985-11-12",
    gender: "female",
    address: "Los Angeles, USA",
    password: "Isabella@123",
    educations: [
      {
        degree_name: "MBA Operations",
        university_name: "UCLA",
        graduation_year: 2010,
      },
      { degree_name: "BBA", university_name: "USC", graduation_year: 2006 },
    ],
    emergency_contacts: [
      {
        name: "James Wright",
        phone: "9100044557",
        address: "Los Angeles, USA",
      },
    ],
  },
  {
    id: "25",
    public_id: "EMP025",
    username: "lucas_adams",
    email: "lucas.adams@example.com",
    phone: "9100055667",
    first_Name: "Lucas",
    last_Name: "Adams",
    full_Name: "Lucas Adams",
    level: 2,

    role: "HR Manager",
    department: "Human Resources",
    date_of_birth: "1988-04-18",
    gender: "male",
    address: "Seattle, USA",
    password: "Lucas@123",
    educations: [
      {
        degree_name: "MBA HR",
        university_name: "Cornell",
        graduation_year: 2012,
      },
      { degree_name: "BBA", university_name: "NYU", graduation_year: 2010 },
    ],
    emergency_contacts: [
      { name: "Emma Adams", phone: "9100055668", address: "Seattle, USA" },
    ],
  },
  {
    id: "26",
    public_id: "EMP026",
    username: "mia_evans",
    email: "mia.evans@example.com",
    phone: "9100066778",
    first_Name: "Mia",
    last_Name: "Evans",
    full_Name: "Mia Evans",
    level: 3,

    role: "Tech Lead",
    department: "Technology",
    date_of_birth: "1990-12-05",
    gender: "female",
    address: "Austin, USA",
    password: "Mia@123",
    educations: [
      { degree_name: "M.Tech", university_name: "MIT", graduation_year: 2015 },
    ],
    emergency_contacts: [
      { name: "Ethan Evans", phone: "9100066779", address: "Austin, USA" },
    ],
  },
  {
    id: "27",
    public_id: "EMP027",
    username: "logan_turner",
    email: "logan.turner@example.com",
    phone: "9100077889",
    first_Name: "Logan",
    last_Name: "Turner",
    full_Name: "Logan Turner",
    level: 3,

    role: "Operations Lead",
    department: "Operations",
    date_of_birth: "1991-03-15",
    gender: "male",
    address: "Denver, USA",
    password: "Logan@123",
    educations: [
      {
        degree_name: "MBA Operations",
        university_name: "Colorado University",
        graduation_year: 2016,
      },
    ],
    emergency_contacts: [
      { name: "Ava Turner", phone: "9100077890", address: "Denver, USA" },
    ],
  },
  {
    id: "28",
    public_id: "EMP028",
    username: "charlotte_baker",
    email: "charlotte.baker@example.com",
    phone: "9100088990",
    first_Name: "Charlotte",
    last_Name: "Baker",
    full_Name: "Charlotte Baker",
    level: 3,

    role: "HR Lead",
    department: "Human Resources",
    date_of_birth: "1992-09-21",
    gender: "female",
    address: "Boston, USA",
    password: "Charlotte@123",
    educations: [
      {
        degree_name: "MBA HR",
        university_name: "Boston University",
        graduation_year: 2017,
      },
    ],
    emergency_contacts: [
      { name: "Henry Baker", phone: "9100088991", address: "Boston, USA" },
    ],
  },
  {
    id: "29",
    public_id: "EMP029",
    username: "elijah_harris",
    email: "elijah.harris@example.com",
    phone: "9100099001",
    first_Name: "Elijah",
    last_Name: "Harris",
    full_Name: "Elijah Harris",
    level: 3,

    role: "Finance Lead",
    department: "Finance",
    date_of_birth: "1987-06-12",
    gender: "male",
    address: "Dallas, USA",
    password: "Elijah@123",
    educations: [
      {
        degree_name: "M.Com",
        university_name: "Texas University",
        graduation_year: 2013,
      },
    ],
    emergency_contacts: [
      { name: "Sophia Harris", phone: "9100099002", address: "Dallas, USA" },
    ],
  },
  {
    id: "30",
    public_id: "EMP030",
    username: "amelia_morris",
    email: "amelia.morris@example.com",
    phone: "9100100112",
    first_Name: "Amelia",
    last_Name: "Morris",
    full_Name: "Amelia Morris",
    level: 3,

    role: "Software Engineer",
    department: "Technology",
    date_of_birth: "1993-11-25",
    gender: "female",
    address: "San Jose, USA",
    password: "Amelia@123",
    educations: [
      {
        degree_name: "B.Tech",
        university_name: "UC Berkeley",
        graduation_year: 2016,
      },
    ],
    emergency_contacts: [
      { name: "Ethan Morris", phone: "9100100113", address: "San Jose, USA" },
    ],
  },
  {
    id: "31",
    public_id: "EMP031",
    username: "jack_wood",
    email: "jack.wood@example.com",
    phone: "9100111224",
    first_Name: "Jack",
    last_Name: "Wood",
    full_Name: "Jack Wood",
    level: 3,

    role: "Tech Lead",
    department: "Technology",
    date_of_birth: "1991-02-18",
    gender: "male",
    address: "Austin, USA",
    password: "Jack@123",
    educations: [
      { degree_name: "M.Tech", university_name: "MIT", graduation_year: 2014 },
    ],
    emergency_contacts: [
      { name: "Emma Wood", phone: "9100111225", address: "Austin, USA" },
    ],
  },
  {
    id: "32",
    public_id: "EMP032",
    username: "harper_evans",
    email: "harper.evans@example.com",
    phone: "9100122335",
    first_Name: "Harper",
    last_Name: "Evans",
    full_Name: "Harper Evans",
    level: 3,

    role: "Operations Lead",
    department: "Operations",
    date_of_birth: "1992-05-12",
    gender: "female",
    address: "Denver, USA",
    password: "Harper@123",
    educations: [
      {
        degree_name: "MBA Operations",
        university_name: "Colorado University",
        graduation_year: 2017,
      },
    ],
    emergency_contacts: [
      { name: "Liam Evans", phone: "9100122336", address: "Denver, USA" },
    ],
  },
  {
    id: "44",
    public_id: "EMP044",
    username: "harper_evans",
    email: "harper.evans@example.com",
    phone: "9100122335",
    first_Name: "Harper",
    last_Name: "Evans",
    full_Name: "Harper Evans",
    level: 3,

    role: "Operations Lead",
    department: "Operations",
    date_of_birth: "1992-05-12",
    gender: "female",
    address: "Denver, USA",
    password: "Harper@123",
    educations: [
      {
        degree_name: "MBA Operations",
        university_name: "Colorado University",
        graduation_year: 2017,
      },
    ],
    emergency_contacts: [
      { name: "Liam Evans", phone: "9100122336", address: "Denver, USA" },
    ],
  },
];
